import * as fs from "fs";
import * as path from "path";

export type FlowStep = {
  type: string;
  targetId?: string;
  value?: string;
  conditions?: Condition[];
  screen?: string;
  direction?: string;
  amount?: number;
};

export type Condition = {
  kind: string;
  nodeId: string;
  expected?: Record<string, unknown>;
};

export type FlowJson = {
  flow: {
    name: string;
    stopOnFailure: boolean;
    timeoutMs?: number;
    steps: FlowStep[];
  };
};

export function generateMaestroYaml(flowJson: FlowJson): string {
  const f = flowJson.flow;
  const lines: string[] = [];

  lines.push(`# Generated by Agent UI — do not edit directly`);
  lines.push(`# Source flow: ${f.name}`);
  lines.push(`appId: com.yourcompany.app`);
  lines.push(`---`);

  for (let i = 0; i < f.steps.length; i++) {
    const step = f.steps[i];
    if (!step) continue;
    lines.push("");
    lines.push(`# Step ${i + 1}: ${step.type}`);

    switch (step.type) {
      case "tap":
        if (step.targetId) {
          lines.push(`- tapOn:`);
          lines.push(`    id: "${step.targetId}"`);
        }
        break;

      case "input":
        if (step.targetId) {
          lines.push(`- tapOn:`);
          lines.push(`    id: "${step.targetId}"`);
          const safeValue = step.value?.startsWith("$") ? `$FIXTURE:${step.value}` : (step.value || "");
          lines.push(`- inputText: "${safeValue}"`);
        }
        break;

      case "scroll":
        if (step.targetId) {
          const dir = step.direction || "down";
          const swipeDir = dir === "down" ? "UP" : dir === "up" ? "DOWN" : dir === "left" ? "RIGHT" : "LEFT";
          lines.push(`- swipe:`);
          lines.push(`    direction: ${swipeDir}`);
          if (step.amount) {
            lines.push(`    duration: ${Math.min(step.amount * 2, 1000)}`);
          }
        }
        break;

      case "navigate":
        lines.push(`# Navigate to: ${step.screen || step.targetId}`);
        if (step.screen) {
          lines.push(`- launchApp:`);
          lines.push(`    clearState: false`);
        }
        break;

      case "waitFor":
      case "assert":
        if (step.conditions) {
          for (const c of step.conditions) {
            const kind = c.kind;
            if (kind === "nodeVisible" || kind === "nodeExists") {
              lines.push(`- assertVisible:`);
              lines.push(`    id: "${c.nodeId}"`);
            } else if (kind === "nodeAbsent") {
              lines.push(`- assertNotVisible:`);
              lines.push(`    id: "${c.nodeId}"`);
            } else if (kind === "nodeState") {
              lines.push(`# State assertion for ${c.nodeId}: ${JSON.stringify(c.expected)}`);
              lines.push(`- assertVisible:`);
              lines.push(`    id: "${c.nodeId}"`);
            }
          }
        }
        break;

      case "observeEvents":
        lines.push(`# observeEvents: ${step.value || "all events"}`);
        break;
    }
  }

  return lines.join("\n") + "\n";
}

export function exportFlowToMastero(
  inputPath: string,
  outputPath?: string
): { success: boolean; error?: string } {
  if (!fs.existsSync(inputPath)) {
    return { success: false, error: `Input file not found: ${inputPath}` };
  }

  let flowJson: FlowJson;
  try {
    const raw = fs.readFileSync(inputPath, "utf8");
    flowJson = JSON.parse(raw);
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return { success: false, error: `Invalid flow JSON: ${msg}` };
  }

  if (!flowJson.flow || !flowJson.flow.steps) {
    return { success: false, error: "Invalid flow structure: missing flow.steps" };
  }

  const yaml = generateMaestroYaml(flowJson);

  const outPath = outputPath || inputPath.replace(/\.json$/, ".yaml");
  try {
    fs.writeFileSync(outPath, yaml, "utf8");
    return { success: true };
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return { success: false, error: `Failed to write output: ${msg}` };
  }
}
