const fs = require("fs");
const path = require("path");
const { spawnSync } = require("node:child_process");
const { generateMaestroYaml, exportFlowToMastero, runMaestroFlow, generateHealProposals, getAgentUICliManifest } = require("../dist/index");

const checkoutFlow = {
  flow: {
    name: "checkout.happyPath",
    stopOnFailure: true,
    timeoutMs: 15000,
    steps: [
      {
        type: "assert",
        conditions: [
          { kind: "nodeExists", nodeId: "checkout" },
          { kind: "nodeState", nodeId: "checkout.confirm", expected: { disabled: false } }
        ]
      },
      { type: "input", targetId: "checkout.shipping.name", value: "Jane Smith" },
      { type: "input", targetId: "checkout.payment.cardnumber", value: "$CARD_FIXTURE" },
      { type: "tap", targetId: "checkout.confirm" },
      {
        type: "waitFor",
        conditions: [
          { kind: "nodeVisible", nodeId: "orderConfirmation.screen" },
          { kind: "nodeState", nodeId: "orderConfirmation.statusLabel", expected: { label: "Confirmed" } }
        ]
      },
      { type: "scroll", targetId: "checkout.shipping.list", direction: "down", amount: 3 }
    ]
  }
};

describe("generateMaestroYaml", () => {
  it("generates valid YAML from checkout flow", () => {
    const yaml = generateMaestroYaml(checkoutFlow);

    expect(yaml).toContain("# Generated by Agent UI");
    expect(yaml).toContain("# Source flow: checkout.happyPath");
    expect(yaml).toContain("appId: com.yourcompany.app");
    expect(yaml).toContain("---");
  });

  it("produces tapOn with id for tap step", () => {
    const yaml = generateMaestroYaml(checkoutFlow);

    expect(yaml).toContain("- tapOn:");
    expect(yaml).toContain('    id: "checkout.confirm"');
  });

  it("produces tapOn + inputText for input step", () => {
    const yaml = generateMaestroYaml(checkoutFlow);

    expect(yaml).toContain('    id: "checkout.shipping.name"');
    expect(yaml).toContain('inputText: "Jane Smith"');
  });

  it("escapes fixture values in input steps", () => {
    const yaml = generateMaestroYaml(checkoutFlow);

    expect(yaml).toContain('inputText: "$FIXTURE:$CARD_FIXTURE"');
  });

  it("produces assertVisible for nodeExists condition", () => {
    const yaml = generateMaestroYaml(checkoutFlow);

    expect(yaml).toContain("- assertVisible:");
    expect(yaml).toContain('    id: "checkout"');
  });

  it("produces assertVisible for waitFor nodeVisible condition", () => {
    const yaml = generateMaestroYaml(checkoutFlow);

    expect(yaml).toContain('    id: "orderConfirmation.screen"');
  });

  it("produces assertVisible for nodeState condition", () => {
    const yaml = generateMaestroYaml(checkoutFlow);

    expect(yaml).toContain("# State assertion for checkout.confirm:");
    expect(yaml).toContain('    id: "checkout.confirm"');
  });

  it("produces assertNotVisible for nodeAbsent condition", () => {
    const flowWithAbsent = {
      flow: {
        name: "test.absent",
        stopOnFailure: false,
        steps: [
          {
            type: "assert",
            conditions: [{ kind: "nodeAbsent", nodeId: "error.toast" }]
          }
        ]
      }
    };
    const yaml = generateMaestroYaml(flowWithAbsent);

    expect(yaml).toContain("- assertNotVisible:");
    expect(yaml).toContain('    id: "error.toast"');
  });

  it("produces swipe for scroll step", () => {
    const yaml = generateMaestroYaml(checkoutFlow);

    expect(yaml).toContain("- swipe:");
    expect(yaml).toContain("direction: UP");
    expect(yaml).toContain("duration: 6");
  });

  it("handles navigate step with screen", () => {
    const flowWithNav = {
      flow: {
        name: "test.nav",
        stopOnFailure: false,
        steps: [{ type: "navigate", screen: "HomeScreen" }]
      }
    };
    const yaml = generateMaestroYaml(flowWithNav);

    expect(yaml).toContain("# Navigate to: HomeScreen");
    expect(yaml).toContain("- launchApp:");
  });

  it("handles observeEvents step", () => {
    const flowWithObserve = {
      flow: {
        name: "test.observe",
        stopOnFailure: false,
        steps: [{ type: "observeEvents", value: "tap events" }]
      }
    };
    const yaml = generateMaestroYaml(flowWithObserve);

    expect(yaml).toContain("# observeEvents: tap events");
  });
});

describe("exportFlowToMastero", () => {
  const fixturesDir = path.resolve(__dirname, "__fixtures__");
  const validFlowPath = path.join(fixturesDir, "valid-flow.json");
  const missingPath = path.join(fixturesDir, "nonexistent.json");
  const invalidPath = path.join(fixturesDir, "invalid-flow.json");

  beforeAll(() => {
    fs.mkdirSync(fixturesDir, { recursive: true });
    fs.writeFileSync(validFlowPath, JSON.stringify(checkoutFlow), "utf8");
    fs.writeFileSync(invalidPath, "not valid json {{", "utf8");
  });

  afterAll(() => {
    fs.rmSync(fixturesDir, { recursive: true, force: true });
  });

  it("succeeds with valid input file", () => {
    const result = exportFlowToMastero(validFlowPath);

    expect(result.success).toBe(true);
    expect(result.error).toBeUndefined();
    const expectedOut = validFlowPath.replace(/\.json$/, ".yaml");
    expect(fs.existsSync(expectedOut)).toBe(true);
    fs.unlinkSync(expectedOut);
  });

  it("returns error for missing file", () => {
    const result = exportFlowToMastero(missingPath);

    expect(result.success).toBe(false);
    expect(result.error).toContain("Input file not found");
  });

  it("returns error for invalid JSON", () => {
    const result = exportFlowToMastero(invalidPath);

    expect(result.success).toBe(false);
    expect(result.error).toContain("Invalid flow JSON");
  });

  it("returns error for missing flow.steps", () => {
    const badPath = path.join(fixturesDir, "bad-structure.json");
    fs.writeFileSync(badPath, JSON.stringify({ flow: {} }), "utf8");
    const result = exportFlowToMastero(badPath);

    expect(result.success).toBe(false);
    expect(result.error).toContain("missing flow.steps");
    fs.unlinkSync(badPath);
  });

  it("writes to custom output path", () => {
    const customOut = path.join(fixturesDir, "custom-output.yaml");
    const result = exportFlowToMastero(validFlowPath, customOut);

    expect(result.success).toBe(true);
    expect(fs.existsSync(customOut)).toBe(true);
    fs.unlinkSync(customOut);
  });
});

describe("runMaestroFlow", () => {
  it("returns MAESTRO_UNAVAILABLE when maestro not installed", () => {
    const result = runMaestroFlow("nonexistent-flow.yaml");

    expect(result.success).toBe(false);
    expect(result.error).toContain("MAESTRO_UNAVAILABLE");
  });
});

describe("generateHealProposals", () => {
  const flow = {
    flow: {
      name: "checkout.happyPath",
      steps: [
        { type: "tap", targetId: "checkout.confirm" },
        { type: "input", targetId: "checkout.shipping.name" },
        { type: "tap", targetId: "checkout.pay" }
      ]
    }
  };

  it("produces proposals for failed steps", () => {
    const results = { failedSteps: [0, 2], errors: ["selector not found", "selector not found"] };
    const heal = generateHealProposals(flow, results);

    expect(heal.proposals).toHaveLength(2);
    expect(heal.proposals[0].originalSelector).toBe("checkout.confirm");
    expect(heal.proposals[1].originalSelector).toBe("checkout.pay");
    expect(heal.failedSteps).toBe(2);
    expect(heal.flowName).toBe("checkout.happyPath");
  });

  it("returns no proposals for passing steps", () => {
    const results = { failedSteps: [], errors: [] };
    const heal = generateHealProposals(flow, results);

    expect(heal.proposals).toHaveLength(0);
    expect(heal.failedSteps).toBe(0);
  });

  it("preserves flow name in result", () => {
    const results = { failedSteps: [1], errors: ["timeout"] };
    const heal = generateHealProposals(flow, results);

    expect(heal.flowName).toBe("checkout.happyPath");
  });

  it("skips steps without targetId", () => {
    const flowNoTarget = {
      flow: {
        name: "test.noTarget",
        steps: [{ type: "navigate", screen: "Home" }]
      }
    };
    const results = { failedSteps: [0], errors: ["navigation failed"] };
    const heal = generateHealProposals(flowNoTarget, results);

    expect(heal.proposals).toHaveLength(0);
  });

  it("provides reason with helpful guidance", () => {
    const results = { failedSteps: [0], errors: ["timeout"] };
    const heal = generateHealProposals(flow, results);

    expect(heal.proposals[0].reason).toContain("inspectTree");
    expect(heal.proposals[0].reason).toContain("checkout.confirm");
    expect(heal.proposals[0].confidence).toBe(0);
    expect(heal.proposals[0].suggestedSelector).toBeUndefined();
  });
});

describe("CLI version", () => {
  const cliPkg = require("../package.json");
  const cliPath = path.resolve(__dirname, "..", "dist", "cli.js");

  it("getAgentUICliManifest returns version matching package.json", () => {
    const manifest = getAgentUICliManifest();
    expect(manifest).toBeDefined();
    expect(manifest.version).toBe(cliPkg.version);
    expect(manifest.packageName).toBe("@agent-ui/cli");
  });

  it("--version flag outputs version string matching package.json", () => {
    const result = spawnSync(process.execPath, [cliPath, "--version"], {
      encoding: "utf8"
    });
    expect(result.status).toBe(0);
    expect(result.stdout.trim()).toBe(cliPkg.version);
    expect(result.stderr).toBe("");
  });

  it("-v short flag outputs version string matching package.json", () => {
    const result = spawnSync(process.execPath, [cliPath, "-v"], {
      encoding: "utf8"
    });
    expect(result.status).toBe(0);
    expect(result.stdout.trim()).toBe(cliPkg.version);
    expect(result.stderr).toBe("");
  });
});
